# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-15 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='joined',
            field=models.DateTimeField(default=None),
        ),
    ]
