# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-21 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0003_auto_20180221_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='', null=True, upload_to='media/profile_pics/'),
        ),
    ]
